### ISSUE TITLE
settings for newtab/home replacement

### ISSUE THREAD

**Issue by tborychowski** [perfect-things/perfect-home#53]
parent: #52
Allow users to choose whether they want to replace the newtab, homepage, both or none.
This would also require the extension to add a button to the addon toolbar, which would open its page.

### Tasks
- [ ] add extension button to the toolbar ([example extension](https://github.com/mdn/webextensions-examples/tree/master/bookmark-it))
- [ ] add settings to allow the user to select pages for newtab & homepage (perfect home | about:blank | about:newtab | custom url)
- [ ] redirect from newtab/homepage to the correct location
