### ISSUE TITLE
Pre-set "library"

### ISSUE THREAD

**Issue by tborychowski** [perfect-things/perfect-home#54]
parent: #52 
Create a "library" of "pre-sets" (e.g. for media-center, small screens, or other weird layouts).

### Tasks:
- [ ] all customisation settings would need to be portable (not only custom CSS), so changing values in form should populate the "custom css" field, e.g.
   ```css
   body  {
      --grid-max-width: 600px;
   }
   ```
- [ ] A static page generated from github folder with screenshot and code to copy & paste
- [ ] a more complex system that would allow to install customizations from cmd palette?
- [ ] allow users to contribute?

**Comment by tborychowski** [comment]
the first version of the "Themes" will arrive in the next release (0.11.0).
